In [24]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [25]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
response = requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers)
print(response.status_code)

200

In [26]:
webpage = response.text

In [27]:
soup=BeautifulSoup(webpage, 'lxml')

In [28]:
soup.title

In [29]:
soup.title.text

'Top Companies in India | AmbitionBox'

In [30]:
for i in soup.find_all('h2'):
  print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [31]:
for i in soup.find_all('p'):
  print(i.text.strip())

AmbitionBox
About Company
All rights reserved © 2026 Info Edge (India) Ltd.
Talk career.
			Stay Anonymous Download the app
Popular
AmbitionBox Award Winner'26
AmbitionBox Award Winner'26
AmbitionBox Award Winner'26
AmbitionBox Award Winner'26
Side-by-side comparison to make informed career
										decisions

In [32]:
company = soup.find_all('div', class_='companyCardWrapper')
print(len(company))

20

In [33]:
company[0].find('h2').text.strip()

'TCS'

In [34]:
for i in company:
    print(i.find('h2').text.strip())

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM

In [35]:
company[0].find_all('div')

[<div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Tata Consultancy Services logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vdGNzLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="TCS">
 									TCS
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(1.2L)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Bengaluru +445 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div> <span class="companyCardWrapper__ratingValues">Job Security</span></div> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div>,
 <div class="companyCardWrapper__companyLogo"><img alt="Tata Consultancy Services logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vdGNzLW9yaWdpbmFsLmpwZw.webp" width="50"/></div>,
 <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="TCS">
 									TCS
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(1.2L)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Bengaluru +445 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div> <span class="companyCardWrapper__ratingValues">Job Security</span></div> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div>,
 <div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="TCS">
 									TCS
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div>,
 <div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="TCS">
 									TCS
 								</h2></a> <!-- --></div>,
 <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(1.2L)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Bengaluru +445 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div> <span class="companyCardWrapper__ratingValues">Job Security</span></div> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div>,
 <div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(1.2L)
 							</span></div>,
 <div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div></div></div>,
 <div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div></div>,
 <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div>,
 <div style="height:auto;">
 			3.3<!-- --></div>,
 <div class="companyCardWrapper__ratingComparisonWrapper"><div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div> <span class="companyCardWrapper__ratingValues">Job Security</span></div> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div>,
 <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div> <span class="companyCardWrapper__ratingValues">Job Security</span></div>,
 <div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div>,
 <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div>,
 <div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div>,
 <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div>,
 <div class="salaryInsightsText">To view salary insights</div>,
 <div class="designationSelectionText">
 							Select designation
 						</div>,
 <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/tcs-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">1.2L</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/tcs-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">10.2L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/tcs-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">11.4k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/tcs-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">4.5k</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/tcs-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">10.8k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/tcs-photos" target="_blank"><span class="companyCardWrapper__ActionCount">93</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div>]

In [36]:
company[0].find('div', class_='rating_text').text.strip()

'3.3'

In [37]:
name = company[0].find('h2').text.strip()

rating = company[0].find('div', class_='rating_text').text.strip()

print(name)
print(rating)

TCS
3.3

In [38]:
company[0].find('span',class_='companyCardWrapper__companyRatingCount')

<span class="companyCardWrapper__companyRatingCount">
								(1.2L)
							</span>

In [39]:
company[0].find('span',class_='companyCardWrapper__interLinking').text.strip()

'IT Services & Consulting | Bengaluru +445 other locations'

In [40]:
spans = company[0].find_all('span')

for idx, i in enumerate(spans):
    print(idx, ":", i.text.strip())

0 : Follow
1 : (1.2L)
2 : IT Services & Consulting | Bengaluru +445 other locations
3 : Highly Rated For
4 : Job Security
5 : Critically Rated For
6 : Promotions, Salary, Work Satisfaction
7 : 1.2L
8 : Reviews
9 : 10.2L
10 : Salaries
11 : 11.4k
12 : Interviews
13 : 4.5k
14 : Jobs
15 : 10.8k
16 : Benefits
17 : 93
18 : Photos

In [41]:
name = company[0].find('h2').text.strip()
rating = company[0].find('div', class_='rating_text').text.strip()
spans = company[0].find_all('span')
reviews = spans[7].text.strip()
salaries = spans[9].text.strip()
interviews = spans[11].text.strip()
jobs = spans[13].text.strip()
benefits = spans[15].text.strip()
photos = spans[17].text.strip()
print(name)
print(rating)
print(reviews)
print(salaries)
print(interviews)
print(jobs)
print(benefits)
print(photos)

TCS
3.3
1.2L
10.2L
11.4k
4.5k
10.8k
93

In [44]:
names = []
ratings = []
reviews = []
salaries = []
interviews = []
jobs = []
benefits = []
photos = []

In [45]:
for i in company:
    spans = i.find_all('span')

    names.append(i.find('h2').text.strip())
    ratings.append(i.find('div', class_='rating_text').text.strip())

    reviews.append(spans[7].text.strip() if len(spans) > 7 else 'N/A')
    salaries.append(spans[9].text.strip() if len(spans) > 9 else 'N/A')
    interviews.append(spans[11].text.strip() if len(spans) > 11 else 'N/A')
    jobs.append(spans[13].text.strip() if len(spans) > 13 else 'N/A')
    benefits.append(spans[15].text.strip() if len(spans) > 15 else 'N/A')
    photos.append(spans[17].text.strip() if len(spans) > 17 else 'N/A')

In [46]:
len(names)

20

In [47]:
df = pd.DataFrame({
    'Company': names,
    'Rating': ratings,
    'Reviews': reviews,
    'Salaries': salaries,
    'Interviews': interviews,
    'Jobs': jobs,
    'Benefits': benefits,
    'Photos': photos})

In [48]:
df

,Company,Rating,Reviews,Salaries,Interviews,Jobs,Benefits,Photos
0,TCS,3.3,1.2L,10.2L,11.4k,4.5k,10.8k,93
1,Accenture,3.7,7.1L,9.4k,35.4k,6.8k,49,N/A
2,Wipro,3.6,4.9L,6.9k,310,4.8k,114,N/A
3,Cognizant,3.7,6.1L,6.5k,711,5.6k,102,N/A
4,Capgemini,3.6,54k,4.9L,5.6k,2.2k,3.8k,42
5,HDFC Bank,3.8,53.1k,1.5L,3.1k,293,3.4k,92
6,Infosys,3.5,"Promotions, Salary, Work Satisfaction",Reviews,Salaries,Interviews,Jobs,Benefits
7,HCLTech,3.4,Reviews,Salaries,Interviews,Jobs,Benefits,Photos
8,ICICI Bank,3.9,1.5L,3k,8,3.8k,73,N/A
9,Tech Mahindra,3.3,2.9L,4.6k,585,3.5k,79,N/A
10,Genpact,3.6,42.9k,2.4L,3.9k,546,3.6k,67
11,TP,3.9,Reviews,Salaries,Interviews,Jobs,Benefits,Photos
12,Jio,4.4,62k,4.5k,--,2.6k,93,N/A
13,Axis Bank,3.6,1L,2k,239,2.2k,121,N/A
14,Concentrix Corporation,3.6,32.6k,1.3L,2k,14,3.2k,67
15,Amazon,3.9,31.8k,1.6L,6k,68,3.7k,95
16,Reliance Retail,3.9,Promotions,Reviews,Salaries,Interviews,Jobs,Benefits
17,iEnergizer,4.6,Reviews,Salaries,Interviews,Jobs,Benefits,Photos
18,LTIMindtree,3.6,2L,3.5k,514,823,34,N/A
19,IBM,3.9,26k,2.2L,2.6k,1.9k,2.6k,23

In [51]:
df.replace(
    ['Reviews','Salaries','Interviews','Jobs','Benefits','Photos',
     'Promotions','Promotions, Salary, Work Satisfaction'],'N/A',
    inplace=True)

,Company,Rating,Reviews,Salaries,Interviews,Jobs,Benefits,Photos
0,TCS,3.3,1.2L,10.2L,11.4k,4.5k,10.8k,93
1,Accenture,3.7,7.1L,9.4k,35.4k,6.8k,49,N/A
2,Wipro,3.6,4.9L,6.9k,310,4.8k,114,N/A
3,Cognizant,3.7,6.1L,6.5k,711,5.6k,102,N/A
4,Capgemini,3.6,54k,4.9L,5.6k,2.2k,3.8k,42
5,HDFC Bank,3.8,53.1k,1.5L,3.1k,293,3.4k,92
6,Infosys,3.5,N/A,N/A,N/A,N/A,N/A,N/A
7,HCLTech,3.4,N/A,N/A,N/A,N/A,N/A,N/A
8,ICICI Bank,3.9,1.5L,3k,8,3.8k,73,N/A
9,Tech Mahindra,3.3,2.9L,4.6k,585,3.5k,79,N/A
10,Genpact,3.6,42.9k,2.4L,3.9k,546,3.6k,67
11,TP,3.9,N/A,N/A,N/A,N/A,N/A,N/A
12,Jio,4.4,62k,4.5k,--,2.6k,93,N/A
13,Axis Bank,3.6,1L,2k,239,2.2k,121,N/A
14,Concentrix Corporation,3.6,32.6k,1.3L,2k,14,3.2k,67
15,Amazon,3.9,31.8k,1.6L,6k,68,3.7k,95
16,Reliance Retail,3.9,N/A,N/A,N/A,N/A,N/A,N/A
17,iEnergizer,4.6,N/A,N/A,N/A,N/A,N/A,N/A
18,LTIMindtree,3.6,2L,3.5k,514,823,34,N/A
19,IBM,3.9,26k,2.2L,2.6k,1.9k,2.6k,23

In [52]:
df

,Company,Rating,Reviews,Salaries,Interviews,Jobs,Benefits,Photos
0,TCS,3.3,1.2L,10.2L,11.4k,4.5k,10.8k,93
1,Accenture,3.7,7.1L,9.4k,35.4k,6.8k,49,N/A
2,Wipro,3.6,4.9L,6.9k,310,4.8k,114,N/A
3,Cognizant,3.7,6.1L,6.5k,711,5.6k,102,N/A
4,Capgemini,3.6,54k,4.9L,5.6k,2.2k,3.8k,42
5,HDFC Bank,3.8,53.1k,1.5L,3.1k,293,3.4k,92
6,Infosys,3.5,N/A,N/A,N/A,N/A,N/A,N/A
7,HCLTech,3.4,N/A,N/A,N/A,N/A,N/A,N/A
8,ICICI Bank,3.9,1.5L,3k,8,3.8k,73,N/A
9,Tech Mahindra,3.3,2.9L,4.6k,585,3.5k,79,N/A
10,Genpact,3.6,42.9k,2.4L,3.9k,546,3.6k,67
11,TP,3.9,N/A,N/A,N/A,N/A,N/A,N/A
12,Jio,4.4,62k,4.5k,--,2.6k,93,N/A
13,Axis Bank,3.6,1L,2k,239,2.2k,121,N/A
14,Concentrix Corporation,3.6,32.6k,1.3L,2k,14,3.2k,67
15,Amazon,3.9,31.8k,1.6L,6k,68,3.7k,95
16,Reliance Retail,3.9,N/A,N/A,N/A,N/A,N/A,N/A
17,iEnergizer,4.6,N/A,N/A,N/A,N/A,N/A,N/A
18,LTIMindtree,3.6,2L,3.5k,514,823,34,N/A
19,IBM,3.9,26k,2.2L,2.6k,1.9k,2.6k,23

In [53]:
df.shape

(20, 8)

In [54]:
df.to_csv('ambitionbox_companies_clean.csv', index=False)